# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Wuazic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios'
 pod 'mobile-ffmpeg-full-gpl', '~> 4.4'
 pod 'SwiftMessages'

 pod 'BoxSDK'

  pod 'AppLovinSDK'
  pod 'AppLovinMediationAdColonyAdapter'
  pod 'AppLovinMediationGoogleAdapter', '~> 11.4.0.0'
  pod 'AppLovinMediationIronSourceAdapter', '~> 7.5.0.0'
  pod 'AppLovinMediationVungleAdapter'
  pod 'AppLovinMediationUnityAdsAdapter'

  pod 'MarqueeLabel'
  pod 'CryptoSwift'
  pod 'SwiftSoup'
  pod 'SDWebImage', '~> 5.0'
   
  pod 'RealmSwift'
  pod 'KeychainSwift'
  
end

#post_install do |installer|
#
#    installer.pods_project.targets.each do |target|
#
#    target.build_configurations.each do |config|
#      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
#
#    end
#  end
#    installer.pods_project.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
#end
